### ISSUE TITLE
Not Recognizing The Unknown Person other than trained people.

### ISSUE THREAD

**Issue by SanatMoharir** [Abhay0899193/Speaker-Recognition#2]
@Abhay0899193 Hey mate,
As I tried your code It is working fine after some dodgy changes. But I have a problem what if I want to identify unknown person Ex. right now it is recognizing an untrained person as one of the trained people. I just want untrained or unknown person as an anonymous person. Can you please help me with this issue?

**Comment by Abhay0899193** [comment]
Hi

For recognising a unknown person we have to make universal background model
which is not implement in the model due to lack of data.

Thank you

**Comment by SanatMoharir** [comment]
Hi, @Abhay0899193 thanks for the reply!
Can you please elaborate on this "Universal Model" I am quite a newbie in this. And how to do this? How to train the universal model and all?

**Comment by Abhay0899193** [comment]
background model is basically GMM with a huge data set. This paper explains
it better...

**Comment by Abhay0899193** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://ieeexplore.ieee.org/document/5713236/&ved=2ahUKEwjX86TghdPlAhWTeisKHYXoDAQQFjACegQIBhAB&usg=AOvVaw1OdpTdG15SS0bx-toQYXYA&cshid=1572956064139
