### ISSUE TITLE
Getting error of ModuleNotFoundError while testing the model against trained data

### ISSUE THREAD

**Issue by Kinjal05** [Abhay0899193/Speaker-Recognition#3]
Hey @Abhay0899193,
I am trying your code in my machine, after some changes it was able to train the model with audio data. But once training is finished, when I clicked on "Test" button, it is giving me below error:
`models    = [pickle.load(open(fname,'rb')) for fname in gmm_files]
` 
`ModuleNotFoundError: No module named 'sklearn.mixture.gmm'`

I am using sklearn version as 0.22 and python version 3.7.
Can you please help with this issue ?

Thank You

**Comment by Abhay0899193** [comment]
Hi

Can you please provide me screen shot of command line error.

thanks

**Comment by Abhay0899193** [comment]
Hi

I can't able to produce this error in system but all problems you faced is due to version you are using. I can understand you want to use latest version but this project is closed two year earlier so we can't update it.
just use these configurations.....
python 3.6
scikit-learn 0.18.1
tk 8.5.18
pillow 4.1.1
numpy 1.12.1

thanks

**Comment by IDKYamHere** [comment]
I was facing the same version when I was working on a voice recognition project.
You must've installed the latest version of scikit-learn, for which the code doesn't work. Downgrade your scikit-learn version to the version given by the owner or scikit-learn==0.19.2 worked for me.
To uninstall and re-install run these two commands :


pip uninstall scikit-learn                                               (to uninstall)
pip install scikit-learn==0.18.1                                     (to install again)

to check the version you're using : 

python
>>> import sklearn
>>> sklearn.__version__
