### ISSUE TITLE
I am getting the following error

### ISSUE THREAD

**Issue by likhitha224** [Abhay0899193/Speaker-Recognition#5]
![Screenshot (91)](https://user-images.githubusercontent.com/60059750/72680713-05f2b200-3ae3-11ea-94f9-27b21ed4d984.png)

**Comment by Abhay0899193** [comment]
Hi
sklearn.mixture.GMM class was removed in 0.20. Use sklearn.mixture.GaussianMixture instead.
or
just use these configurations.....
python 3.6
scikit-learn 0.18.1
tk 8.5.18
pillow 4.1.1
numpy 1.12.1

Thanks

**Comment by Abhay0899193** [comment]
please let me know this will solved your issue or not.

**Comment by likhitha224** [comment]
Thank you so much for responding back.
I tried whatever you told me to do but still i'm getting the following
error.
PFA of screenshots of error message,program and package version.
Please do reply me back soon.

**Comment by likhitha224** [comment]
Should i do any changes in this part ?

**Comment by Abhay0899193** [comment]
Hi

Attachments are not visible to me.
send it to abhay000singh@gmail.com

thanks

**Comment by likhitha224** [comment]
Pass me ur email id,i shall mail to u...

**Comment by likhitha224** [comment]
Found your email. Thanks i shall mail it

**Comment by Abhay0899193** [comment]
Hi

you are using sklearn 0.22.1 use 0.18.1.

or change sklearn.mixture.gmm to sklearn.mixture.GaussianMixture in every
code.

thanks

**Comment by likhitha224** [comment]
Hi...I change sklearn.mixture.gmm to sklearn.mixture.GaussianMixture in
every
code but still I am getting error. I have mailed the error. Pls do check.

**Comment by Abhay0899193** [comment]
I will reproduce this error in my system tonight.

**Comment by likhitha224** [comment]
Okay and let me know once the error is fixed.
